# Colors
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced # dark
# export LSCOLORS=ExFxBxDxCxegedabagacad # light

# config home
# case "$__OS" in 
# Darwin)
#   export XDG_CONFIG_HOME=$HOME/.config
#   export XDG_DATA_HOME=$HOME/.local/share
#   export XDG_CACHE_HOME=$HOME/.cache
#   ;;
# esac

# Brew
case "$__OS" in
Darwin)
    eval "$(/opt/homebrew/bin/brew shellenv)"
    ;;
esac

# Browser
case "$__OS" in
Darwin)
  export BROWSER='open'
  ;;
Fedora)
  export BROWSER='firefox'
  ;;
esac

# Editors
export EDITOR='$HOME/.local/bin/vi-ed'
export VISUAL='$HOME/.local/bin/vi-ed'
export PAGER='bat'

# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Paths
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
# PATH=/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
path=(
  /opt/homebrew/{bin,sbin}
  /usr/local/{bin,sbin}
  /System/Cryptexes/App/usr/bin
  /usr/{bin,sbin}
  /{bin,sbin}
  $path
)


# Less
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# asdf
# case "$__OS" in
# Darwin)
#   source $(brew --prefix)/opt/asdf/libexec/asdf.sh
#   ;;
# Fedora)
#   # 
#   ;;
# esac

# Add .NET Core SDK tools
export PATH="$PATH:/Users/ra/.dotnet/tools"
