#!/bin/zsh

# stop interpreting Ctrl+S as a command to pause output
# stty -ixon

# Load the compinit module, and configure it dynamically based on the .zcompdump file's age
# - '#q' is an explicit glob qualifier that makes globbing work within zsh's [[ ]] construct.
# - 'N' makes the glob pattern evaluate to nothing when it doesn't match (rather than throw a globbing error)
# - '.' matches "regular files"
# - 'mh+24' matches files (or directories or whatever) that are older than 24 hours.
autoload -Uz compinit
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
	compinit -i;
else
	compinit -C;
fi;

# Disable the NOMATCH option which allows non-matching patterns to be passed as-is
setopt +o nomatch

# Enable emacs keybindings in the shell
bindkey -e

source ~/.zshrc.d/_history.sh
source ~/.zshrc.d/_edkeys.sh

# Load the 'url-quote-magic' widget which performs URL quoting in the ZLE (Zsh Line Editor)
autoload -U url-quote-magic

# Redefine the self-insert function to include 'url-quote-magic' functionality
zle -N self-insert url-quote-magic

# Function to bring the most recent background job to the foreground
# Assign the function to a keybinding for easy access
function foreground-current-job() {
  fg
}
# Attach the 'foreground-current-job' function to a zle widget
zle -N foreground-current-job
# Bind the function to Ctrl+Z in emacs keymap
bindkey -M emacs '^z' foreground-current-job

alias zreload='exec zsh -l'

function prepend-sudo() {
  # about 'add sudo before the current command or remove it if already present'
  [[ -z $BUFFER ]] && zle up-history
  if [[ $BUFFER == sudo\ * ]]; then
    LBUFFER="${LBUFFER#sudo }"
  else
    LBUFFER="sudo $LBUFFER"
  fi
}
zle -N prepend-sudo
# add sudo before command with esc+esc
# defined shortcut keys: [Esc][Esc] conflicts with AstroNvim
bindkey "\e\e" prepend-sudo

# User specific aliases and functions
if [ -d ~/.zshrc.d ]; then
	for rc in ~/.zshrc.d/*; do
		if [ -f "$rc" ]; then
			source "$rc"
		fi
	done
fi
unset rc

function quiet() {
  # about 'what *does* this do?'
  $* &>/dev/null &
}

export PKG_CONFIG_PATH="$(brew --prefix)/lib/pkgconfig:$PKG_CONFIG_PATH"

# User specific aliases and functions
if [ -d ~/.zshrc.d ]; then
	for rc in ~/.zshrc.d/*; do
		if [ -f "$rc" ] && [[ $(basename "$rc") != _* ]]; then
			source "$rc"
		fi
	done
fi
unset rc

# prevent strange control sequences after ssh disconnect
stty -ixon

export PATH=".:$PATH"
source ~/.zshrc.d/_fzf.sh
source ~/.zshrc.d/_atuin.sh
source ~/.zshrc.d/_starship.sh

export TERM=xterm-256color